### ISSUE TITLE
Creating a new account throws an error

### ISSUE THREAD

**Issue by ronanversendaal** [vswarte/laravel-ledger#2]
When creating a new account from an existing user :
```
$user = User::find(1);

$account = $user->createAccount("example", "description");
```
Throws an error in the `Accountable` trait: 

```
Argument 1 passed to Illuminate\Database\Eloquent\Relations\HasOneOrMany::save() must be an instance of Illuminate\Database\Eloquent\Model, array given, called in ..../vendor/vswarte/laravel-ledger/src/Accountable.php on line 21
```

This is because the trait calls `save` on the model, which expects a `Model`, but an array is passed. Changing the method to `create` allows for passing arrays.

**Comment by vswarte** [comment]
resolved per #1
