### ISSUE TITLE
Getting the Id of a new transaction

### ISSUE THREAD

**Issue by nholliday** [vswarte/laravel-ledger#6]
It would be handy to be able to get the id of the transaction created by the createTransaction function of the TransactionFactory, so that for example it can be logged against another model to which it relates.

Perhaps the following would work:

```
    public static function createTransaction(
        array $mutations,
        string $description
    ) {
        return DB::transaction(function () use ($mutations, $description) {
            $transaction = LedgerTransaction::create([
                'description' => $description,
            ])->fresh();

            $transaction->mutations()->saveMany($mutations);
            return $transaction->id;
        }, 5);
    }
```

**Comment by vswarte** [comment]
I'll work on fixing all the issues you've created on Thursday/Friday. Feel free to create a PR in the meanwhile though. :-)

**Comment by nholliday** [comment]
New to all of this but I *think* I've submitted the pull requests correctly!

Thanks

**Comment by vswarte** [comment]
Yo yo, sorry for the horribly late response.
In short: I've been switching jobs a lot since I wrote this, but I am back and will be starting to maintain this project again.

Thanks for the PR!
